package:
  name: hyphalnet
  version: "0.1"

source:
  git_rev: 
  git_url: https://github.com/sgosline/hyphalnet

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - hyphalnet

about:
  home: https://github.com/sgosline/hyphalnet
